# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  WORKSPACE = "Godrm.xcworkspace"
  PROJECT = "Godrm.xcodeproj"
  TESTING_SCHEME = "Debug testing"
  SCHEME_FOR_BETA = "Development"

  desc "Testing app"
  lane :test do
    run_tests(
      workspace: WORKSPACE, 
      devices: ["iPhone 13 Pro"], 
      scheme: TESTING_SCHEME
    )
  end
end
